In [5]:
using JLD2, FileIO, Knet

loadfile = "/Users/rishi/Project/GAN/invert/models/0040.jld2"

function convert_weights(w, atype=Array{Float32})
    w0 = map(wi->convert(atype, wi), w)
    w1 = convert(Array{Any}, w0)
end


function convert_moments(moments,atype=Array{Float32})
    clone = map(mi->bnmoments(), moments)
    for k = 1:length(clone)
        if moments[k].mean != nothing
            clone[k].mean = convert(atype, moments[k].mean)
        end

        if moments[k].var != nothing
            clone[k].var = convert(atype, moments[k].var)
        end
    end
    return convert(Array{Any,1}, clone)
end

convert_moments (generic function with 2 methods)

In [7]:
@load loadfile wd wg md mg
        wd = convert_weights(wd)
        wg = convert_weights(wg)
        md = convert_moments(md)
        mg = convert_moments(mg)

4-element Array{Any,1}:
 Knet.BNMoments(0.1, Float32[0.00308741; 0.0376763; … ; -0.0853855; 0.0275474], Float32[0.108245; 0.113723; … ; 0.132705; 0.138851], zeros, ones)
 Knet.BNMoments(0.1, Float32[-0.119358; -0.0440976; … ; -0.460867; 0.0406191], Float32[0.0954573; 0.101038; … ; 0.110588; 0.117891], zeros, ones)
 Knet.BNMoments(0.1, Float32[1.01312; -1.33131; … ; 0.0456956; 2.04858], Float32[0.593872; 0.770849; … ; 0.704336; 0.865449], zeros, ones)       
 Knet.BNMoments(0.1, Float32[-0.807624; -0.242992; … ; -0.806992; -0.883706], Float32[0.577206; 0.521696; … ; 0.378443; 0.533384], zeros, ones)  

In [14]:
for i = 1:10
    println(size(wg[i]))
end

println(wg[2])

(200, 100)
(400,)
(400, 200)
(800,)
(600, 400)
(1200,)
(784, 600)
(1568,)
(784, 784)
(784, 1)
Float32[0.988231, 1.01135, 0.98884, 1.00093, 1.0106, 0.999613, 1.001, 1.00691, 1.00466, 0.993783, 1.01823, 0.99563, 0.993865, 0.973963, 0.992096, 0.9995, 0.982372, 1.00643, 0.995911, 1.0158, 1.02071, 0.981914, 0.980509, 1.00978, 0.990956, 1.00194, 0.978214, 0.974401, 1.00278, 0.996806, 0.978213, 0.980177, 1.00813, 0.986086, 1.00761, 1.0211, 0.994596, 0.974433, 0.964279, 1.00778, 1.0149, 1.02926, 1.00574, 0.984441, 1.00506, 0.973829, 1.01142, 0.983778, 1.00245, 1.0039, 0.979708, 0.983985, 1.01778, 1.032, 0.993934, 1.04366, 1.00732, 0.984208, 0.997591, 0.967023, 0.995792, 1.00544, 0.995781, 1.0074, 0.988058, 0.98813, 1.00247, 1.02748, 0.990664, 0.977971, 1.00289, 0.955066, 0.965629, 1.02204, 1.01261, 0.98734, 1.02475, 0.969568, 1.01202, 0.967733, 0.995209, 0.989719, 0.969157, 0.991114, 0.978628, 0.985847, 0.978984, 0.96465, 1.00652, 1.02687, 0.991009, 1.006, 0.975968, 0.995438, 0.992173, 0.98187

In [21]:
im = randn(28,28,784)
for j = 1:784
    im[:,:,j] = reshape(wg[9][:,j], 28, 28)
end

In [22]:
using Plots, Interact

@manipulate for k = 1:784
    heatmap(im[:,:,k])
end

Interact.Options{:SelectionSlider,Any}(9: "input-3" = 392 Any , "k", 392, "392", 392, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8,"9"=>9,"10"=>10…), Dict{Any,Any}(Pair{Any,Any}(306, "306"),Pair{Any,Any}(29, "29"),Pair{Any,Any}(74, "74"),Pair{Any,Any}(176, "176"),Pair{Any,Any}(285, "285"),Pair{Any,Any}(318, "318"),Pair{Any,Any}(354, "354"),Pair{Any,Any}(610, "610"),Pair{Any,Any}(563, "563"),Pair{Any,Any}(671, "671")…)), Any[], Any[], true, "horizontal")

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 5 
 
 
 10 
 
 
 15 
 
 
 20 
 
 
 25 
 
 
 5 
 
 
 10 
 
 
 15 
 
 
 20 
 
 
 25 
 
 
<image width="491" height="364" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAAesAAAFsCAYAAADsRpHBAAAYEklEQVR4nO3d23Pfd5kf8EeWZNmS
D/JRdnxM7MSOTWzIgRycsBAgJAS64bDQ6QLbpZSZ3dJ0l/amM+10ptx0OrsXdDodhu40BYa2sBBI
lgwswZsQEsiRxMQkPsV2ZDu2fJQl2bKO7h/xPDvzuXi9/oD3vPXT4a3vzffp2H3Hp65GgZtve7Ui
Js4Ork5nPHtwa0GTiK3Lh9IZ+8+tLGgS8bFdz6UznnhuV0GTiDuuO5jO6OycKWgS8cyBG9MZH9qx
p6BJxNvH1qQzhq/0FjSJOH9lfknOyFR3OuMzu54taBLx7Wf+IJ3R1TFb0CTi07e9lM64cnleQZOI
3fu250M6SmYgPrjljXTG/uPrC5pEXLvyVDrjsX3bCppE3Ng/nM6YU9ADAPhHZKwBoHHGGgAaZ6wB
oHHGGgAaZ6wBoHHGGgAaZ6wBoHHGGgAaZ6wBoHHGGgAaZ6wBoHEdRz9zW8kb3E8N1RysOH9pYTrj
XZsOFTSJePJ3705n7NqUP3oREbH/nfyRiI6CHhERb40sSmcMXckfiIiIuGHR5XTGngt9BU0iblk6
ms5Yu+hiQZOIV06vKsn5y699O53xra/904ImEUt6rqQz5nVNFTSJODOe/5npLeqya2f+EM3lkQUF
TSL2H8sf4diyfrCgScSZc0vTGY8fvragScTDH3w6neHJGgAaZ6wBoHHGGgAaZ6wBoHHGGgAaZ6wB
oHHGGgAaZ6wBoHHGGgAaZ6wBoHHGGgAaZ6wBoHEdT935yZJDHsdHF1fElLzc/o3hmi5/dv+T6Yzn
X7qloEnE2Svz0xk/f6fmZf1/esM76YzN644VNIn4D7tvT2d8+caawwGXp3rSGc+dqjmIs7Z3oiRn
58DJdMYzx9cVNIm4Y1W+y8zVmnM2Q2P5g0NzOkr+9Mbo1Nx0xvyu6YImNTm33LC/oEnEviP5IxzL
FowUNIkYGDiTzvBkDQCNM9YA0DhjDQCNM9YA0DhjDQCNM9YA0DhjDQCNM9YA0DhjDQCNM9YA0Dhj
DQCNM9YA0LiOX7/v4yVvk9+x66WKmBjcszWdMTPTWdAk4pVjG9MZU0WHAyYKvqZnT+df+B8RsbY3
/zVVHTHYtPBKSU6Fzf3n0xkHLywraBKxfcVQSc6vTqxNZ5y5UvP7eN/a/Nd0ZKTmyE/FQZAdy08X
NIn46WD+e3RT/2hBk4hbr30rnfHTfdsLmkQMT3alM96/5kRBk4jliy6mMzxZA0DjjDUANM5YA0Dj
jDUANM5YA0DjjDUANM5YA0DjjDUANM5YA0DjjDUANM5YA0DjjDUANK7r2PCSkqDXHv0nJTkPvGtP
OmNioqegScTmpWfTGY/s21DQJGJxwQ2O4anpfEhEzF7OH2b4ow3DBU0i9lzoT2c8eu5UQZOIT1y6
Jp2xsHumoEnE+ct9JTlbFucPEHzkujMFTSKOFxw52brkXEGTiOOji9IZLw+tKmgSsaFvIp0xPpM/
ehER0b8if8xm19jbBU0iHj24OZ2xZmXNsZWrswXHjwp6AAD/iIw1ADTOWANA44w1ADTOWANA44w1
ADTOWANA44w1ADTOWANA44w1ADTOWANA44w1ADSuY899H7paEbRsef4F7hERL7yxLZ2xY8ORgiYR
P967M51xteTTjXjtQv5F+0MTkwVNIro78v/j/ezSNwuaRHxj65+mM341NL+gScTJifxBhc9trDm2
sqQn3yUiYk7HbDrj3ZsPFjSJGB1dmM+41FvQJOJ3p1enMzYszB9JiYh49eyKdMb5yZrntrkFMe9e
WvO5LJ1/KZ1xfHRxQZOI6dn8B+PJGgAaZ6wBoHHGGgAaZ6wBoHHGGgAaZ6wBoHHGGgAaZ6wBoHHG
GgAaZ6wBoHHGGgAaZ6wBoHFdswUvGI+IeOb1HSU5ywtevv7S4esLmkTsWnMsnfH44Y35IhFxcGIk
nXFuztmCJhHzr+aPIXR11rwg//DovHTG5GzNtZUvbcofz+iImi6LesZLclYvPZfO+F8v3F7QJOLh
j/59OuP//uT+giYRFT8yU0V/e9f1XU5nLO3JHwqKiPjfgzPpjKtR87dhRU/+79QXPry7oEnEL567
M53hyRoAGmesAaBxxhoAGmesAaBxxhoAGmesAaBxxhoAGmesAaBxxhoAGmesAaBxxhoAGmesAaBx
HS994IGSywHz5k5WxMTY+Px0xtlLCwuaRDw2uCKdMZl/r31EROy/MprO2NVf87mcz9+riP3jY/mQ
iBjoyr+sf+/sYEGTiLWzq9IZ5zvy3+eIiP90fWdJzqGRRemMydmOgiYRT52eTmf0zKn5XO5bNZvO
+OVQzfGMgfn5Z667VtT8Pq5ekP/5PXBhaUGTiAuT+c93fV/NQZybVp1IZ3iyBoDGGWsAaJyxBoDG
GWsAaJyxBoDGGWsAaJyxBoDGGWsAaJyxBoDGGWsAaJyxBoDGGWsAaFzXa6fWlATd/+7fluScPbo4
nXGu4BhIRMSWRfnDAdcurDnM0NmRPxxw13t2FzSJ+M4v35fO+K8PPV/QJOKJ39yZzvjwdP4AR0TE
s2fmpTNunJvPiIj43fn8z0tExDvj+f/nl/WU3AqKL23KX5DpnlPzudx37y/TGSOPfrygScSPzpxN
Z9yytK+gScTJsfyxoJmrNYdfHtr6ZjrjzPCSgiYRPzp4fTrDkzUANM5YA0DjjDUANM5YA0DjjDUA
NM5YA0DjjDUANM5YA0DjjDUANM5YA0DjjDUANM5YA0DjuuZ1zpQETU91l+R0Frxof/vAqYImEcuX
5V+Qf/TE2oImEX/9+up0xupFG/NFIuLhv/lFOuPsIzXHVj73F99NZ5x/flNBk4htb25JZ1yZrvk9
On255jDD8csL0hknLtccZti8sCudcc/m/QVNIno/lu/y76/9m4ImEV89sTSd8f3HHyhoEjE9m3/+
+8iWNwqaRGy859V0xtvf/1hBk4ijY/nPxZM1ADTOWANA44w1ADTOWANA44w1ADTOWANA44w1ADTO
WANA44w1ADTOWANA44w1ADTOWANA4zr2f/yeqxVBLxzeXBETG/svpDMGlp4raBKxYv3JdMb4cP4Q
QkTE/3z27nTGV+5/sqBJRP8D5/Mh0zUHZKInf/hiYsutBUUius8MpjPmHHmroEnEySe2luSsvDl/
+OL73/pMQZOIjYvzP3c773yloElE1xfzn+/s/MUFTSJ6fvpEOqNkBCLi7PM3pDOefvXmgiYRh0bz
x2y+dM+zBU0ifrcvf+THkzUANM5YA0DjjDUANM5YA0DjjDUANM5YA0DjjDUANM5YA0DjjDUANM5Y
A0DjjDUANM5YA0DjulbfcLQk6LoLS0pyNm8+nM7o/9f5F7hHRBz7zwPpjFU35r+eiIi+rvzhi+/+
wwcKmkR8+c/2pjM6n3m5oEnEyO835EN+ciifERFz1p/KhyyczWdERN/SiyU5j3770+mMj9zxfEGT
iJnprnTG6KnlBU0iFm/8cDqj56mvFzSJmLl9Zzpjzgt7CppEXJ3NP/9tHcgfUIqIePe6iXTG6PCi
giYRx8fyOZ6sAaBxxhoAGmesAaBxxhoAGmesAaBxxhoAGmesAaBxxhoAGmesAaBxxhoAGmesAaBx
xhoAGtcx9MXtVyuCZqbyL9mPiDh8JH+YYc2qo

In [23]:
335,16, 25, 169, 171+e, 210, 222, 255, 265, 283, 366, 384, 416, 432, 447, 448, 457, 459, 466, 489, 496, 507, 508

(335, 16, 25, 169, 173.71828182845906, 210, 222, 255, 265, 283, 366, 384, 416, 432, 447, 448, 457, 459, 466, 489, 496, 507, 508)

In [47]:
im = reshape(sum(wg[9], 2)+wg[10], 28,28)
heatmap(tanh.(im))

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 5 
 
 
 10 
 
 
 15 
 
 
 20 
 
 
 25 
 
 
 5 
 
 
 10 
 
 
 15 
 
 
 20 
 
 
 25 
 
 
<image width="491" height="364" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAAesAAAFsCAYAAADsRpHBAAAQRklEQVR4nO3d66/ld1XH8fU7s8/c
OtOWW2emBaQ40IINVKIICoVIUmuiJhSICSRlSoBIYwgaqkGFByIXI15So0WMZaSTYgARERtAgyAG
SKGSNgHEBtC2lAKlt+ncztlnbx+Y+IRKTL6L9OPm9foDVtbZs895z+/Jb03z5ZFlrZjZdOihXqHd
fHl4eEbX59KxS5eOn6nr51nF712HVfx8V+13oEvS59Ih6bNde6gXAAC+N7EGgHBiDQDhxBoAwok1
AIQTawAIJ9YAEE6sASCcWANAOLEGgHBiDQDhxBoAwk1phzxW7TBD1C6Lw8Mzqqpma4da5vDdkr4v
VVkHZHhwScczkv5mdkj6PfJkDQDhxBoAwok1AIQTawAIJ9YAEE6sASCcWANAOLEGgHBiDQDhxBoA
wok1AIQTawAI13bIYxVf1r+KL5RP0XVUpKbxEUkv61+1f2f+f0j6W8eD82QNAOHEGgDCiTUAhBNr
AAgn1gAQTqwBIJxYA0A4sQaAcGINAOHEGgDCiTUAhBNrAAjXdshjFTmqAPB/t2rHbJIOnHiyBoBw
Yg0A4cQaAMKJNQCEE2sACCfWABBOrAEgnFgDQDixBoBwYg0A4cQaAMKJNQCEmyW9NL0q68XpSaaG
GUkXW9am9ZY5y+Xm+IyGPdJ0fF+qej6bqWmbZcM2SZ/LKtr48pHhGV0NSGvbKE/WABBOrAEgnFgD
QDixBoBwYg0A4cQaAMKJNQCEE2sACCfWABBOrAEgnFgDQDixBoBw03x5JOqd9B0vX096EfzDdv3I
+CJVdd/JW4ZnLJcbDZtU7Vg/MDxjvjjesElVx2mG+da9DXusplU7IDNNPc8ny+WiZQ4/GDqa5Mka
AMKJNQCEE2sACCfWABBOrAEgnFgDQDixBoBwYg0A4cQaAMKJNQCEE2sACCfWABBu1jao4ehFl65d
jp982/CM03b9esMmVbXcahjScZah6onrzxqecXt9uWGTqvVp1/CMu05+sWGTqsXW0YYpPf9GXecz
OqasrY3/G1VVLZenhmfs3v6Yhk2qTmzeOTxjsRj/ebpkfetyJB2F8mQNAOHEGgDCiTUAhBNrAAgn
1gAQTqwBIJxYA0A4sQaAcGINAOHEGgDCiTUAhBNrAAg3zZdHot693vHC82PH3zy+SFXt2f1bDVO6
Dirk/DMd2PPM4Rn7Fo9t2KTqphPvG57x8F0XNGxStazF8Ix7TnypYZOqru/dzvX9wzMevv3xDZtU
3XHs08Mzuo6KnL59/Pt7bPObDZtUbczvapnToeMgSM5fuj4dB0E8WQNAOLEGgHBiDQDhxBoAwok1
AIQTawAIJ9YAEE6sASCcWANAOLEGgHBiDQDhxBoAwk1Vs5b3pne8qLyq55BHl6nhtfRdBzg6djlj
15MaNqk6Mf/O8Izz15/TsEnVrto5POPGjQ81bFK1tTgxPGO53GjYpGq27YyWOcvl+HGStWm9YZOq
Zc2HZ/zo+s81bFL18h+aDc+44pYPNGxStVyeGp6xaPreLZfj/0ZJjh777ZY5e097w/AMT9YAEE6s
ASCcWANAOLEGgHBiDQDhxBoAwok1AIQTawAIJ9YAEE6sASCcWANAOLEGgHAOeXwPa9P24RnTtK1h
k6r9u39seMbX/v4bDZtU1U+9dnjE8oarGhap+sRrzhueccnnrm/YpGrjb/cMz7j5jy5s2KTqNz/z
wy1zbljeMDzjVY98ZsMmVW+69e3DM6a18d/pqqrPPvfZwzO+9K0DDZtUXfqCvxuecfrvjB9sqaqa
b93fMofv5skaAMKJNQCEE2sACCfWABBOrAEgnFgDQDixBoBwYg0A4cQaAMKJNQCEE2sACCfWABBu
mi+PtBzySDrAkeTKc17VMufP7v7Y8Izbb7+4YZOqafP48IyXnddzUOFdV147POM1V13WsEnVwb2b
wzNe/W9Pa9ik6vqnf7xlzgtvHj9ystg62rBJ1csfdcXwjNnUsEhVvfeBTw/P2LP28IZNqs7aOnt4
xudOva9hk6qp4flvsRj/+1JVtazxtM0Xh8cXqapq+N55sgaAcGINAOHEGgDCiTUAhBNrAAgn1gAQ
TqwBIJxYA0A4sQaAcGINAOHEGgDCiTUAhGs75NFl1Q6C7Fjf1zLn6idcMjzjb27b2bBJ1ZVP+frw
jOd+6iMNm1T94cGXDs943a0fbdik6uTmt4ZnfPUFT27YpOqsC77SMufC37toeMbFex7TsEnVJed8
e3jGRR8/v2GTqh27xo9nPP7M6xo2qfrni08Mzzj4/hsbNqmqadv4jOXW+IzqOeSRxJM1AIQTawAI
J9YAEE6sASCcWANAOLEGgHBiDQDhxBoAwok1AIQTawAIJ9YAEE6sASDc7KFeYNX9zM7nt8x51S3v
H55xy6Xjxweqqh73ni8Mz7j3vtc2bFJ14FHvHp5x178+bnyRqlr70PihiW2n39ywSdW3P3Vey5xX
7ts/PGPP7GTDJtVyluGN59/VMKXqDV8ef8754E9sb9ik6tG/du/wjKd++EUNm1TddPw9wzNW6/xG
H0/WABBOrAEgnFgDQDixBoBwYg0A4cQaAMKJNQCEE2sACCfWABBOrAEgnFgDQDixBoBws9l0qGXQ
fHm4Zc6q+ceN61vmTA3/rzp6/96GTao+9oyfHZ6x+x/+pGGTqqkeMTxjzwWfbtik6lcOvGJ4xpt/
9S8aNqk665KvtMx58TR+VmHXmUcbNqm6+XMXDs/47D2nGjap2vW+Nw3PmG89r2GTqmPXjn++n/zK
zoZNql508JXDMz587B0Nm6weT9YAEE6sASCcWANAOLEGgHBiDQDhxBoAwok1AIQTawAIJ9YAEE6s
ASCcWANAOLEGgHDTfHlk/E39jboOi6TYsX5Wy5x9Oy4YnvH0bec1bFK1d30annH1R25o2KTq+DV3
Dc848I7jDZtUnb790cMz7jr2+YZN+qzPHjk845rzL2nYpOqyL/zV8Izjb1lv2KTqXYd/cXjG79/2
nYZNqu5c/PvwjGdte07DJlXXP5BzhGNZOWmbLw4Pz/BkDQDhxBoAwok1AIQTawAIJ9YAEE6sASCc
WANAOLEGgHBiDQDhxBoAwok1AIQTawAI13bIY9UOcHSZavzoRZed289umXP05JuGZxx77W80bFJ1
39fHD6U86QP3NmxSdWLzG8Mzlst5wyZ91qYdD/UK/+O0HY8ZnnHlvueOL1JVN949/nt97S2bDZtU
nXHguuEZZ+482LBJ1bHNbw3POLX5zYZNssyXh4dneLIGgHBiDQDhxBoAwok1AIQTawAIJ9YAEE6s
ASCcWANAOLEGgHBiDQDhxBoAwok1AIRrO+TRpmGb2dqh8SEraG2t5yhDz7GJngMnV5z1yuEZ193/
iYZNqn5y27OGZ3xncaJhk6qb5h9rmbO1ODk848wd5zZsUvX6c54yPOPKr13fsEnVxtbdwzPO3f3T
DZtUvfHcRwzPOH37qYZNqn7h8x8cnrFcbDRsUrXsiEkQT9YAEE6sASCcWANAOLEGgHBiDQDhxBoA
wok1AIQTawAIJ9YAEE6sASCcWANAOLEGgHBxhzxm06GHeoVIPWcveqZcsucVwzM+eNU1DZtUXfTL
Lx6ecXDnnoZNqv70i+NHL04/8JcNm1StTT1HW

In [62]:
z = randn(100,1)
z = relu.(wg[7]*(relu.(wg[5]*(relu.(wg[3]*(relu.(wg[1]*z)))))))
z = tanh.(wg[9]*z+wg[10])
heatmap(reshape(z,28,28))

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 5 
 
 
 10 
 
 
 15 
 
 
 20 
 
 
 25 
 
 
 5 
 
 
 10 
 
 
 15 
 
 
 20 
 
 
 25 
 
 
<image width="491" height="364" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAAesAAAFsCAYAAADsRpHBAAAYAUlEQVR4nO3deZfmdXkm8Lv26qW6
qvemm256Y9+R5YgoIgliggMquBBHGIyaMwmcRD1m1DFjopmMjMcwcQYSHWNEJY5LIlscwyIkoBAE
FWi2Rrqhu6G7eq9eqmufF3Hfc873j8/nBVznqqfqea76/fPcHZPfHZqJAjNz51TExOh570lnfPSE
yYImEfeMPpfOWD+9tqBJxA+Hj05nXLbk5YImEXdtHEtn9G59uqBJxEUXnZnOePCvvl3QJOKtN1yb
zlg7pzdfJCKeO3S4JGc0xtMZP/3TfyhoEvHez12bzvjJxL+kMyIidh3+RDpj/LN/WNAk4p1ffHc6
48BM/j0dEXHP41vSGV0/eqigScTEOy9LZ1x+0oKCJhGPTef/7joLegAA/x8ZawBonLEGgMYZawBo
nLEGgMYZawBonLEGgMYZawBonLEGgMYZawBonLEGgMYZawBoXPfU5pqjFx39u0tyLr/yUDrjnq98
q6BJxOW/d2064/a//tt8kYg4ftlvpDM2/OeaIwaXHJs/HLA/ji9oEnHN8vzhi0tuuKagScQxs/Jd
bvnCVwqaRLzpD64uyfnZ3T9LZ1z7zusKmkRMz0ynM07pOLegScQlc/41nXHGUM3v6Pb784cvOnfv
KGgSsf6cU9IZL3y2o6BJRP8Dd6QzFvR8qKBJxO6bXkpneLIGgMYZawBonLEGgMYZawBonLEGgMYZ
awBonLEGgMYZawBonLEGgMYZawBonLEGgMYZawBoXMf4Tf0zFUErPn16RUwsn1mbznh55pmCJhG7
vpf/cvuD9/YXNIm48CvnpzOuWjK/oEnEYG/++Mvv/fE3CppE3PnlK9MZ929fUNAk4qabv53OuOra
9xU0ieiMmmMIfV35nOPn5Q9wRET8dFc+549PqzlY8ftP5l+XlbG4oEnEYzP5Yyvbf1Lz3Da5cGU6
Y2pgeUGTiNn3fTOdMbN4UUGTiJlntqczPFkDQOOMNQA0zlgDQOOMNQA0zlgDQOOMNQA0zlgDQOOM
NQA0zlgDQOOMNQA0zlgDQOOMNQA0rmP8yzWHPDqOrflS+ti0M59R9C/I3X/zrnRGX1f+6EVExIOv
LUlnvH3N5nyRiLjnlWPSGStnHyloEtHTOZXOOG/tiwVNInbuyx9KmdNX87qsOGZrSc4zzx6fzvjR
K0cXNImYKfik6qi5bxKHJvNBPzmQP+4QEXFsZ/6z4TPn1LwHjv/anHTGG07uK2gSce6c/BGOL33w
ewVNImadNZrO8GQNAI0z1gDQOGMNAI0z1gDQOGMNAI0z1gDQOGMNAI0z1gDQOGMNAI0z1gDQOGMN
AI0z1gDQuI7rFt1QcsjjxcP5LyqPiLj3C99MZ8yMdhc0ifjEX16Xzlg3d6ygSURXZ/7XND5V87/Z
rK788Yx1Q/sKmkT0d4+nM5YvHS5oErH51eXpjNm9NX8vPd3531GV6ema6xkbho9KZ9y/PX9oIiJi
/0T+9d0w83JBkxofXrKqJOe6i+9PZ8y/tOb9uOj9K9IZrz0yWNAkomv/7nSGJ2sAaJyxBoDGGWsA
aJyxBoDGGWsAaJyxBoDGGWsAaJyxBoDGGWsAaJyxBoDGGWsAaJyxBoDGdYz92+tKDnlMzZ1fERMX
nJ3/sv5Hfvx4QZOIm655czrj1aKjInN78r+mYwcOFTSJOHPFK+mMqema/xNHx/vSGQsHa46KHBnL
d9k9UnM4YOfhuSU5Jy3fks7Yd3CgoEnEwbH+dMa+I7MKmkQMFBxc+eyzvQVNIo7ty//NbB47WNAk
4rpVXemMm185XNAkomLYTuxbWJAS8c1vfCed4ckaABpnrAGgccYaABpnrAGgccYaABpnrAGgccYa
ABpnrAGgccYaABpnrAGgccYaABpnrAGgcR3j968vOeTx0at/qyImTho8ks74p209BU0iThnK/y8z
VfLqRqyeM57O6O6cLmgSsW88//qes3R7QZOIlUt2pDMOHZ5d0CRi064l6YyHdtQcDij6s4uOgoy3
rXq1ICVi3qz8gYcXC35HERGHJvLvgV/urTkqsuXwVDrj368dKWgScePG/CGP4c6av5e9U1vTGZs/
mD/YEhHxu7fm99GTNQA0zlgDQOOMNQA0zlgDQOOMNQA0zlgDQOOMNQA0zlgDQOOMNQA0zlgDQOOM
NQA0zlgDQOM6Ju5dW/Kd/1OP7aqIiU99+dp8xmU/zheJiDseuiCd8cD2OQVNIo6bl/+y/rMX7yxo
ErFqyXA6Y/OOZQVNIo5ekP+76+3NH0mJiPjRcyenMx7bXXOEZvPYoZKcy5f1pTMuWJE/qBAR0d2Z
fw9Mz1ScJomYmOpOZ2zZP1TQJOLhnfPSGbvHak6/vDaeP8S0vLe/oEnEQE/+d71tdLKgScQPHn46
neHJGgAaZ6wBoHHGGgAaZ6wBoHHGGgAaZ6wBoHHGGgAaZ6wBoHHGGgAaZ6wBoHHGGgAaZ6wBoHHd
1199WUnQF3+2pSTnqc9NpDOu/95bC5pEXLzscDqju+jfof0T+aCuzpov6+8qOKhw9hm/KmgS0dmd
73L7g28qaBIxWHAQZNtY/ueJiDh5Ts0BmRdG8hmnLpidD4mIuX35IxFrj3m5oEnErp2L0hkvbVtR
0CRiXk/+fb3l8HRBk4hV/bPSGZuO5D93IyK2TuY36Wfv2F7QJGLe6/I5nqwBoHHGGgAaZ6wBoHHG
GgAaZ6wBoHHGGgAaZ6wBoHHGGgAaZ6wBoHHGGgAaZ6wBoHHGGgAa19HVOVBy3eHI3YMVMXHRuy5N
Z1y4MP9l8hERQ72T6Yxf7OkpaBKxvOAWwjvWbsqHRMT8gQPpjMEFewuaRDy78dh0xhM7lxQ0iTh5
wZ50xthkd0GTiI0j80py+rryBx4WFxzgiIg4c9XmdMbg/H35IhFxYH/+9V189GsFTSI+dFv+cNG6
gY6CJhGHJ/M5+/L3cCIiYsdYPuio/t6CJhHDY/kDVZ6sAaBxxhoAGmesAaBxxhoAGmesAaBxxhoA
GmesAaBxxhoAGmesAaBxxhoAGmesAaBxxhoAGte9f+PFJUGnn1ZzgOD47v50xl8O31XQJOLtsy5L
Z0zPlNxJiYW9U+mMkSMF10Aioq8n/6X0M7sXFDSJmJrJHw44a8lwQZOI5/fkf6bTl2wvaBLx6K75
JTlbD+Xf12vm1hyzOXUq32Vwdc3xjN7hsXTG8JblBU0ibnzLE+mM//bw2QVNIk4dyh/PmK75yIzp
yH82XHX2wwVNIhb/p/yuebIGgMYZawBonLEGgMYZawBonLEGgMYZawBonLEGgMYZawBonLEGgMYZ
awBonLEGgMYZawBoXPfM7IUlQU888KuSnHUX7U5ndHbUHA4Y7M1/EfzLhyYLmkTsHKs5lFLhiVdX
pjNWDewvaBKxYuGudMbeA/MKmkSsmZf/mf5t+4qCJhFXrN1UkvPVZ9amM1bOOVLQJOKhzfkuc+Yc
KmgSseKcDemM5549rqBJxOze/FGRgZqPzPj+tvzn3QULZhU0iRifzn9+X33HmQVNIrbd9Wo6w5M1
ADTOWANA44w1ADTOWANA44w1ADTOWANA44w1ADTOWANA44w1ADTOWANA44w1ADTOWANA47o7D+wo
Ceo8WHOYYcn0CemMM7tPKmgS0Z3/HvhY0ldzg

In [63]:
U, S, V = svd(wg[9])

(Float32[-0.0598811 0.00396198 … -0.00617001 -0.043583; 0.060708 0.0110732 … 0.0165003 0.0024091; … ; -0.0598847 -0.00626777 … -0.0637692 0.0189898; 0.0479015 0.00183554 … 0.00412501 0.00287086], Float32[6.72789, 3.51064, 3.42191, 3.35229, 3.26899, 3.18015, 3.09476, 3.07169, 2.95923, 2.9091  …  0.00653564, 0.00650379, 0.00525344, 0.00477571, 0.00335073, 0.00261482, 0.00164768, 0.0010524, 0.000607012, 0.000184681], Float32[-0.029906 -0.0919841 … 0.0148009 0.027084; 0.000674129 0.0117658 … 0.0371892 -0.0402425; … ; -0.0457206 0.00394607 … -0.0450733 -0.0589776; -0.0791885 0.0380086 … -0.00162788 -0.0425886])

In [65]:
@manipulate for k = 1:784
    heatmap(tanh.(reshape(U[:,k],28,28)))
end

Interact.Options{:SelectionSlider,Any}(17: "input-5" = 392 Any , "k", 392, "392", 392, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8,"9"=>9,"10"=>10…), Dict{Any,Any}(Pair{Any,Any}(306, "306"),Pair{Any,Any}(29, "29"),Pair{Any,Any}(74, "74"),Pair{Any,Any}(176, "176"),Pair{Any,Any}(285, "285"),Pair{Any,Any}(318, "318"),Pair{Any,Any}(354, "354"),Pair{Any,Any}(610, "610"),Pair{Any,Any}(563, "563"),Pair{Any,Any}(671, "671")…)), Any[], Any[], true, "horizontal")

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 5 
 
 
 10 
 
 
 15 
 
 
 20 
 
 
 25 
 
 
 5 
 
 
 10 
 
 
 15 
 
 
 20 
 
 
 25 
 
 
<image width="491" height="364" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAAesAAAFsCAYAAADsRpHBAAAYcElEQVR4nO3d63PWhZnG8etJnpwJ
5EQgIRBSAyQEEBDk5IogYl3Es9TFUm1du1ZLO7a7dt3pOlO3a6vbWdupra1V165Va7tWVAq1aoEq
cgYhQEJCOIWDCYQgJJBz9sX+Cfe9M/eL7+cPuOYiz+Hi9+a5E6fvrxqUgwtn8zxitKb2cnNGVUGb
QxNpZL49Z/fxcocmUumQ8+aMZEq/QxNp8sxPzBlH949zaCKtPTjenJGX3uvQRCrPtb9GxbmfOTSR
crIvuuR8c90kc8bPFtvfL5L0zOYZ5ox7auodmki/rZ9gzvjanC0OTaSjJ0aZM/Id3ruS9PzuGnPG
t/5ms0MTadSiPeaMXa8tdGgi/by20pyR4tADAAD8P2KsAQAIjrEGACA4xhoAgOAYawAAgmOsAQAI
jrEGACA4xhoAgOAYawAAgmOsAQAIjrEGACA4xhoAgOAS87O/6nLI42zC54fgF+QWmzO+t+wdhyZS
78VMc0bt3okOTaTRxS3mjL6+pEMT6eU9k80ZD8zb5NBEysrtNGecOlbm0ETq6bX/fZOpPsdW8vJ8
DoJ80mQ/QPBc4zCHJtKXL+swZ/ztkncdmkgaTJgj5v9ksUMRaUKG/YjSs19+06GJVLfDfoip7vQI
hybSF7/9ijmj/vfzHJpIqQ5HlHiyBgAgOMYaAIDgGGsAAIJjrAEACI6xBgAgOMYaAIDgGGsAAIJj
rAEACI6xBgAgOMYaAIDgGGsAAIJjrAEACC5xoXm5yyGPJ+YUesTolspD5ozqGXscmkjffOlWc8aC
ERccmkjXTttlzsirOOHQRNr34UxzRkXlYYcm0i/fX2jOKMrscWgifdSaZc747txPHJpIaWm9LjkH
msvNGYvufsuhibTqpTvNGXkZlxyaSBnJPnPGxd50hyZSR0+GOWNG5QGHJlJGdpc5Y2iZ/WiRJB3Y
MtWcccnhbytJu1pHmjN4sgYAIDjGGgCA4BhrAACCY6wBAAiOsQYAIDjGGgCA4BhrAACCY6wBAAiO
sQYAIDjGGgCA4BhrAACCY6wBAAguceewlS6HPFZOavaIUUpiwJxROqLVoYlUekWdOWPVb29xaCIN
OrxKFQVt9hBJlVWN5ozPWgscmkh9fUlzxrbDlQ5NpMtHHTNnVN/9sUMT6bPNZS45D776eXPGy4//
yqGJtO43N5kzCof4HNYZP73WnLH63UUOTaRkiv07874D2xyaSKunTzBnFOe3OzSRMjPtR0Ve2mY/
WiRJDyzcYM7gyRoAgOAYawAAgmOsAQAIjrEGACA4xhoAgOAYawAAgmOsAQAIjrEGACA4xhoAgOAY
awAAgmOsAQAIjrEGACC45FPXbXUJKhx7wiXHw0Cv/biDJNWvu9KcMTS926GJNP+GD8wZ3/nV3zk0
ka5qLzRnVBa1ODSRahZsMWccbR3p0ESqXrnPnPGbR5Y7NJFSHY47SFJ+esKccfg9n2MIBTn2Ixw1
Czc5NJF62oaZMxJyuaGkHzemmTNerZnq0ESqmbzTnJFVfNahiZQxvtOc8Z1JTQ5NpFO148wZPFkD
ABAcYw0AQHCMNQAAwTHWAAAEx1gDABAcYw0AQHCMNQAAwTHWAAAEx1gDABAcYw0AQHCMNQAAwTHW
AAAEl/h1zVdcfk0+M7XPI0bZab3mjGcP5Ds0kfLT7AdBbiv3+VH6qZ+z/6B8Z2eOQxNp38lR5oyN
p+2HECTpykL7cYeq4T5HRfoGUs0ZtU5HRRZP2uOS09tjPxIxZo5Pl7oPZpszWs/nOTTx8Wx9sUvO
L25bb8545i8L7EUkzS0+bc6oGHHKoYnU12//PL7bOMGhifSlazaYM3iyBgAgOMYaAIDgGGsAAIJj
rAEACI6xBgAgOMYaAIDgGGsAAIJjrAEACI6xBgAgOMYaAIDgGGsAAIJjrAEACC6575zPcYe89AGX
nGTCflfk8SsPOTSROrqyzBlZ6T0OTaSUlH5zxtZjY+1FJPUM2P+Pl5Xqcj9Gy//5dXPGC/9+t0MT
aULBGXPGnHKf9+6/rZ/lkvPYwk3mjMYNMxyaSJuax5ozrqvaby8iqa55jDnj5QffcGgiHdg61ZzR
dCHh0ERauajWnDE44NOl6Loj5ow9P7S/zpKUVXTOnMGTNQAAwTHWAAAEx1gDABAcYw0AQHCMNQAA
wTHWAAAEx1gDABAcYw0AQHCMNQAAwTHWAAAEx1gDABAcYw0AQHDJoWk+Bzjy03tdch5s+G9zxv5q
nyMGo8c2mzNOnxzh0EQ6eqLMnHHvE6scmkhn3ioxZ1w873NA5rUnv2DOWHbdBw5NpP2fTDJnNLWO
dGgiHbvoc0Cm7Ma95oy6V+Y6NJEOd2SaMzov2o/zSFJHb7o5o3HbFIcmUkF+uznj148959BE6mga
Zc747u+XODSRZm/rMGfkZ15yaCJteH++OYMnawAAgmOsAQAIjrEGACA4xhoAgOAYawAAgmOsAQAI
jrEGACA4xhoAgOAYawAAgmOsAQAIjrEGACA4xhoAgOCS80cddwl641C5S84DxV81Z+w9fs6hiXRt
hf1vc65jiEMTqaUz15zx+r/e6NBESiTsGTUlPu+73gH7/zdPNI61F5GUmtJvzhiS3u3QRFo2Jtsl
p+9Emjmjty/p0ET68uV7zBlD8847NJEaGiaYMz5/9UGHJtKJJvt3b93aqxyaSDUrPjZn7Hqx06GJ
dF/NSXPGO02VDk2k3fZbKzxZAwAQHWMNAEBwjDUAAMEx1gAABMdYAwAQHGMNAEBwjDUAAMEx1gAA
BMdYAwAQHGMNAEBwjDUAAMEx1gAABJfYcs2SQY+gfoeDCpI07dqN5oy962c5NJEmXFFrznjuzaUO
TaTS7EvmjAXTdzg0kQ4dqjBnzPrmhw5NpJ8/usyccaHX59BEdtJ+yGNCnsMv/ksaW9ziktP4aak5
Y/qEeocm0o76anPGlZP2OjSR2s8UmDOaWkocmkhFORfMGYV5PsePzp0fas5IT+t1aCJNfminPaS7
x54h6ejrNeYMnqwBAAiOsQYAIDjGGgCA4BhrAACCY6wBAAiOsQYAIDjGGgCA4BhrAACCY6wBAAiO
sQYAIDjGGgCA4BhrAACCSw4vbHMJGjr8rEtOb0e2OaOwwOcYQmpWtzmjLOeiQxNpbvU+c0ZdwziH
JtLeM8PNGSce9zlwsuCyg+aMMRMbHZpI546PMGcUjT/q0ET6w6olLjlzx9uPcPR2pzs0kXr6U80Z
R46McWgijSw+bc5o7850aCJd6LX/fV+stx/nkaQf3vauOePMCfvnSJJ+9sgd5oxJhfbXWZKmz9xl
zuDJGgCA4BhrAACCY6wBAAiOsQYAIDjGGgCA4BhrAACCY6wBAAiOsQYAIDjGGgCA4BhrAACCY6wB
AAiOsQYAILjEp/dOGvQI2r1/okeMatsKzRn9gwmHJtKVIz41Z4wo8DmU0ttj/7H+/Z+Ocmgi1ZQe
N2fk5Z9zaCIVT7Ef4fj60/c4NJFmFF4yZyyZtsOhiZSR3eWSs3uv/XPd2590aCJd99Aqc8bPnrjX
XkTSlCL7gYeSgjMOTaS+Pvvf91JPhkMTaWDA/vzX75AhSWUlp8wZ3V0+f5fmVvtxEp6sAQAIjrEG
ACA4xhoAgOAYawAAgmOsAQAIjrEGACA4xhoAg

In [67]:
using JLD2, FileIO, Knet

loadfile = "/Users/rishi/Project/GAN/invert2/models/0040.jld2"


"/Users/rishi/Project/GAN/invert2/models/0040.jld2"

In [70]:
@load loadfile wd wg md mg
        wd2 = convert_weights(wd)
        wg2 = convert_weights(wg)
        md2 = convert_moments(md)
        mg2 = convert_moments(mg)

4-element Array{Any,1}:
 Knet.BNMoments(0.1, Float32[-0.161142; 0.0366402; … ; -0.117736; -0.264277], Float32[0.126143; 0.166973; … ; 0.128428; 0.116013], zeros, ones)   
 Knet.BNMoments(0.1, Float32[-0.459579; -0.197176; … ; 0.348573; -0.351009], Float32[0.199852; 0.193774; … ; 0.366214; 0.270826], zeros, ones)    
 Knet.BNMoments(0.1, Float32[-0.311432; -0.131385; … ; 0.63795; -0.0359346], Float32[1.43124; 0.530333; … ; 0.752069; 0.417069], zeros, ones)     
 Knet.BNMoments(0.1, Float32[-0.0314631; -0.0811415; … ; 0.00948229; -0.483889], Float32[0.482277; 0.945397; … ; 0.903251; 0.446786], zeros, ones)

In [71]:
U2, S2, V2 = svd(wg2[9])

(Float32[-0.0545027 -0.0105084 … -0.00110292 -0.0334312; 0.0558997 0.00742005 … -0.0617146 0.00678279; … ; 0.0509322 0.00746312 … 0.0602752 -0.0128693; -0.0464596 -0.00548544 … 0.011883 -0.0485194], Float32[6.03795, 3.63256, 3.53766, 3.52104, 3.32577, 3.1962, 3.17807, 3.12364, 3.03848, 2.94599  …  0.00605359, 0.00528161, 0.00477763, 0.0047176, 0.00380903, 0.00358568, 0.0019778, 0.00168216, 0.000810503, 0.000374557], Float32[0.0331715 0.0129348 … -0.0509187 -0.0142197; 0.0189621 0.0251105 … -0.0147128 -0.00415559; … ; 0.0351406 0.0543512 … -0.0167933 0.0375413; 0.0272424 -0.0209474 … -0.0249143 0.0506])

In [72]:
@manipulate for k = 1:784
    heatmap(tanh.(reshape(U2[:,k],28,28)))
end

Interact.Options{:SelectionSlider,Any}(21: "input-6" = 392 Any , "k", 392, "392", 392, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8,"9"=>9,"10"=>10…), Dict{Any,Any}(Pair{Any,Any}(306, "306"),Pair{Any,Any}(29, "29"),Pair{Any,Any}(74, "74"),Pair{Any,Any}(176, "176"),Pair{Any,Any}(285, "285"),Pair{Any,Any}(318, "318"),Pair{Any,Any}(354, "354"),Pair{Any,Any}(610, "610"),Pair{Any,Any}(563, "563"),Pair{Any,Any}(671, "671")…)), Any[], Any[], true, "horizontal")

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 5 
 
 
 10 
 
 
 15 
 
 
 20 
 
 
 25 
 
 
 5 
 
 
 10 
 
 
 15 
 
 
 20 
 
 
 25 
 
 
<image width="491" height="364" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAAesAAAFsCAYAAADsRpHBAAAYkUlEQVR4nO3deXfVhbnF8X3gJGQg
CRAICQkJEGKYRQEZLjI4IaIoSp1qK8Va9Trc1rbXTloramur1daqVVq0dai9WlurYqHIIMokMzLP
JMwkQAYSEpLcF/E8d61n3fX9vIC9dnJyzs7vn/MkHiu5r00OSjqe8YhRRvKcOePa3650aCJdN+VS
c8ac6Z86NJFeXTLOnHH9oE0OTaStlcXmjGS7Vocm0sLD3cwZ3xn/mUMT6Ux9pjlj4/5e5gxJSiRc
YjS8bLs54+TJTg5NpEE/3G3OeOfbFzs0kc62tDdn1J1LOjSRZt70njnjOy/f4tBEyk+zv6+n9N7r
0ETKzGgwZ7S1+ryRuhYcM2e0c+gBAAD+DzHWAAAEx1gDABAcYw0AQHCMNQAAwTHWAAAEx1gDABAc
Yw0AQHCMNQAAwTHWAAAEx1gDABAcYw0AQHCJX5Xe43LIY8bExR4x2rq13JzRNeeUQxOp4WyaOSMl
2ezQRGprs/9f1f+6pQ5NpHbp9ow2nzseevrxmeaMj442OTSRXpu0xZyxfm+pQxPpyJkMl5ycVPvv
ZtKoFQ5NpNoq+0GQ7RUlDk2kZLsWc8YlP1psLyLp81+ONWcsP1Lg0ER68LtzzBk7Phjj0ERaurev
OcPr4NCJxlRzBk/WAAAEx1gDABAcYw0AQHCMNQAAwTHWAAAEx1gDABAcYw0AQHCMNQAAwTHWAAAE
x1gDABAcYw0AQHCMNQAAwSU2XzXR5ZBH72fsX1QuSW9MKzZnfHnK4dKEpPSk/VczubjSoYk05MKN
5oxj+wodmkhHqnPNGS9uLnJoIr11aqQ5Y+fVsx2aSEWDd5gzmmt9DnAM+5P9II4knd+ujznjuUmr
HJpIl39sPzbxaK/ODk2km773tjmjdq3P8YzUnDpzRuWGfg5NpA82DzJnpLRzmSSVd6o2Z5zff5tD
Eymzu70LT9YAAATHWAMAEBxjDQBAcIw1AADBMdYAAATHWAMAEBxjDQBAcIw1AADBMdYAAATHWAMA
EBxjDQBAcIw1AADBJR9bZv/idUnaOvyES86LFxw1Z+ypK3FoIv14WZU549RD+x2aSBvXDjFnrD/W
3aGJ9P1975kzHus53aGJNCFzsTljwcPr7EUkNZ/qaM7YtnGAQxNp0WT7+0iStu7LMmes31Xm0ETq
1ppmzhhdvtmhifTcrG+YM0Z0P+zQRKpvsv9ernjgfYcm0om1Q80ZX55qdWgibTiZb864dOY/HZpI
3370W+YMnqwBAAiOsQYAIDjGGgCA4BhrAACCY6wBAAiOsQYAIDjGGgCA4BhrAACCY6wBAAiOsQYA
IDjGGgCA4BhrAACCS04vOeUSdPX0j11y2uc0mjNKlvscQ9h7Z2dzRo9e9Q5NpAv/bv9S+tF/et2h
iXT92n7mjDnLff5PnD1xpznjgV/PsBeRNCG/xpxR15zi0EQ6WpftktPc2t6ckdPB/p6WpAUP2T9j
Xnr9JocmUk5qszmjd89KhyZSS4v9Nape0tuhiZTars2c8d6sOQ5NpHufvNOc8cHLPgeHqpvsGTxZ
AwAQHGMNAEBwjDUAAMEx1gAABMdYAwAQHGMNAEBwjDUAAMEx1gAABMdYAwAQHGMNAEBwjDUAAMEx
1gAABJc4fmc/+zevS2p1+DJ5SVq0erg5o6RTlUMTaXd1N3NGavsWhyZSk8Pvd0TvXQ5NpNKvbzJn
PPzg1xyaSJOLK8wZJYUHHZpIS7cMMmdsPNnRoYl018jVLjlrdpeZM6ZM9Tny0+PpPHPGsYU+n1Mr
v9fHnLHheHeHJlLPzDpzRmGnaocmUtLh825/lf1z18uU+//mkvPyL243Z/BkDQBAcIw1AADBMdYA
AATHWAMAEBxjDQBAcIw1AADBMdYAAATHWAMAEBxjDQBAcIw1AADBMdYAAATHWAMAEFxiwcjpLoc8
DtdnecRob12GOeP7d77h0ESa+bT9y9fLs1sdmkgPfdP+Mz0x2+d4Rt+senNGSsLn99I5rdGcMeKC
9Q5NpMbaTHOGy5tR0upt/V1yLui705zR7c/THJpI7wy3d+njdLBi+ZECc0ZaO5/3wJCux80ZHx4o
dGgiXdf7gDlj7v6eDk2km/tvM2ecczpQteRAb3MGT9YAAATHWAMAEBxjDQBAcIw1AADBMdYAAATH
WAMAEBxjDQBAcIw1AADBMdYAAATHWAMAEBxjDQBAcIw1AADBJZNOXya/8IjPIY9FjTvMGf3/51qH
JtILX/3QnPHeJ5c4NJFWzLXntDpdieiRWWvOqG60H2yRpAlvnDJnPHbZ5Q5NpCuLK80ZB053dmgi
VZ1Ndcn5YsVF5oyf/uZJhybS+P724yQ1NdkOTaSaZvuBhxmXfurQROo67ag5Y/m3b3RoIr25s9ic
8ZvKcocm0u159owXb/3YHiJpT5W9DE/WAAAEx1gDABAcYw0AQHCMNQAAwTHWAAAEx1gDABAcYw0A
QHCMNQAAwTHWAAAEx1gDABAcYw0AQHCMNQAAwSV+WnKfy3mHGSO+8IhR0V3HzBnzfjDKoYl03fr5
5oy/nT/JoYnU2mb/v2p4+VaHJlLl4QJzRltrwqGJVHWmozkjN7POoYnU2mp/jRqbUxyaSPtrOrnk
TLpwjTnjrRWjHZpIvTraX6dR/bY4NJFqa+yHi0ovXuvQRKqvsB+J+GDJxQ5NpGONaeaMUQWHHJr4
vJcmfvMDhybSmW0c8gAA4P89xhoAgOAYawAAgmOsAQAIjrEGACA4xhoAgOAYawAAgmOsAQAIjrEG
ACA4xhoAgOAYawAAgmOsAQAILvH+hbe6HPJoPJf0iNHgogPmjF1Hejg0kcaNW2bO6Dje50jE9tmD
zRmJhMtLrT5j7QcI/vGXaQ5NpBd3pZozPrr/I4cm0qol9oMV/cp2OTSRPl49wiXn+ksWmTOueXWC
vYikt69dZ854Y4XPkZ+SjmfMGXtqMx2aSPdOnWvOKPtDV4cm0vbbT5kz9m4vdWgitXP4vDtyurND
E2niNfajUDxZAwAQHGMNAEBwjDUAAMEx1gAABMdYAwAQHGMNAEBwjDUAAMEx1gAABMdYAwAQHGMN
AEBwjDUAAMEx1gAABJdofiXN5bpD2zmPFGn5G1eaM8rP2+3QRKo+lmvO+N2aIQ5NpJwU+8tUnlPv
0EQqzz1uzhg0yn4MRJJWLx1pzsjocNahibS0oticcc+t7zo0kX4252aXnJvKd5ozahoyHJpIf9pR
ZM6Y/dQrDk2kTW+PN2ekpfr83f1ihf0z5vnb33doIu3fXGbO6Nrd/vkiSZldT5ozfvnutQ5NpG2n
7Rk8WQMAEBxjDQBAcIw1AADBMdYAAATHWAMAEBxjDQBAcIw1AADBMdYAAATHWAMAEBxjDQBAcIw1
AADBMdYAAASXmNn1AZdDHrefV+ERo2Hjl5szzjV0cGginazMN2d0yGhwaCJldK4xZ3z4yUSHJtIN
t7xnzvjZS193aCLNGLrBnFH8tM+hiacm9TVnjM475tBEGj/13y45RzfZf6ZV2/o7NJHGD19jznh2
/iUOTaQrig6ZM46d6ejQRNpda8+Z1n+zQxOp+Pxt5oy96wY4NJE+2tHPnFGWbf/claTLL19szuDJ
GgCA4BhrAACCY6wBAAiOsQYAIDjGGgCA4BhrA

In [73]:
function leaky_relu_inverse(x,alpha=0.2)
    pos = max(0,x)
    neg = min(0,x)/alpha
    return pos + neg
end

leaky_relu_inverse (generic function with 2 methods)

In [77]:
println(size(mg[1].mean))

(200, 1)


In [78]:
function inverse_batchnorm(x,moments,params)
    (N,m) = size(x)
    
    scale = params[1:N]
    bias = params[N+1:end]
    
    m = moments.mean
    v = moments.variance
    
    for i = 1:N
        x[i,:] = (((x[i,:] .- bias[i]) .* (1/scale[i])).*v[i]).+m[i]
    end
    
    return x
end
        

inverse_batchnorm (generic function with 1 method)

In [79]:
function inverse_glayer(w,x,m)
    x = leaky_relu_inver.(x)
    x = inverse_batchnorm(x,m,w[2])
    x = pinv(w[1])*x
    return x
end

inverse_glayer (generic function with 1 method)

In [121]:
x = randn(3,2)

3×2 Array{Float64,2}:
 -2.25693   -1.07236 
 -2.12875    2.1918  
 -0.913284   0.283669

In [122]:
m = bnmoments()

Knet.BNMoments(0.1, nothing, nothing, zeros, ones)

In [123]:
y = batchnorm(x,m;training=true)

3×2 Array{Float64,2}:
 -0.999986  0.999986
 -0.999999  0.999999
 -0.999986  0.999986

In [131]:
(1/(y[1,1]/(x[1,1]-10*m.mean[1])))^2*0.1+0.9

0.9350813326576883

In [129]:
m.var

3×1 Array{Float64,2}:
 0.93508 
 1.36668 
 0.935817

In [128]:
m.mean

3×1 Array{Float64,2}:
 -0.166464  
  0.00315287
 -0.0314807 

In [112]:
1/sqrt((m.var[1]-0.9)/0.1+1e-5)

1.0000004302729593

1×1×3×2 Array{Float64,4}:
[:, :, 1, 1] =
 0.999995

[:, :, 2, 1] =
 0.999972

[:, :, 3, 1] =
 -0.999971

[:, :, 1, 2] =
 -0.999995

[:, :, 2, 2] =
 -0.999972

[:, :, 3, 2] =
 0.999971